// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Actualización de datos-correo error y corregido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Actualización de datos-correo error y corregido', async function() {
    await driver.get("https://nntp-frontend-dev.nntp-dev.protectasecuritycloud.pe/intranet")
    await driver.manage().window().setRect({ width: 1294, height: 694 })
    await driver.findElement(By.css(".react-responsive-modal-overlay")).click()
    await driver.findElement(By.linkText("Actualización de datos")).click()
    await driver.executeScript("window.scrollTo(0,135)")
    await driver.findElement(By.css("div:nth-child(3) > .sc-ehCJOs .row-container:nth-child(1) .sc-hKwDye:nth-child(2) .injected-svg")).click()
    {
      const element = await driver.findElement(By.css(".input-row-active"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".input-row-active"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".input-row-active"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".input-row-active")).click()
    await driver.findElement(By.css(".input-row-active")).click()
    await driver.findElement(By.css(".input-row-active")).sendKeys("orlando.joshepgmail.com")
    await driver.findElement(By.css(".container-buttons > .sc-gsDKAQ")).click()
    await driver.findElement(By.css(".input-row-active")).click()
    await driver.findElement(By.css(".input-row-active")).sendKeys("orlando.joshep@gmail.com")
    await driver.findElement(By.css(".container-buttons > .sc-gsDKAQ")).click()
    await driver.executeScript("window.scrollTo(0,4.375)")
    await driver.findElement(By.css(".modal-success-button > .sc-gsDKAQ")).click()
    await driver.findElement(By.css(".modal-success-button > .sc-gsDKAQ")).click()
  })
})
